In [2]:
import pandas as pd

df = pd.read_csv('data/camh/simdata_long_n100.csv')

In [72]:
df.loc[df.id=='sub69']

id  period  msex  geno1  geno2  geno3  time      img1       img2  \
366  sub69       0     1      3      3      1     0  7.942824  11.050807   
367  sub69       1     1      3      3      1     6       NaN        NaN   
368  sub69       2     1      3      3      1    12  6.386433   8.181420   
369  sub69       3     1      3      3      1    18       NaN        NaN   
370  sub69       4     1      3      3      1    24       NaN        NaN   
371  sub69       5     1      3      3      1    30  3.696298   5.931797   
372  sub69       6     1      3      3      1    36  4.268842   4.541949   
373  sub69       7     1      3      3      1    42  3.452485   2.120400   
374  sub69       8     1      3      3      1    48  3.920347   1.664505   
375  sub69       9     1      3      3      1    54  4.246697   4.301326   
376  sub69      10     1      3      3      1    60  2.883523   2.674891   
377  sub69      11     1      3      3      1    66  1.881854   2.246408   

         img3       cog1       cog2       cog3        ses  
366 -2.075689   8.252405  18.057623  17.236605  26.968101  
367       NaN   6.764888  14.526613  17.475498  21.688457  
368  4.868396   3.183381  12.364513  23.861694  12.945550  
369       NaN   0.596725   9.860425  26.114127  10.136811  
370       NaN  -1.784479   6.234164  27.597313   0.595799  
371  1.705776  -3.210402   4.062567  34.508350  -3.402739  
372  1.382950  -6.003822   1.939546  35.342976  -6.366126  
373  1.793578  -8.782625   1.987248  41.977552  -9.162012  
374 -0.055124 -10.841635  -1.153497  47.021450 -18.016193  
375  4.902001 -11.404033  -2.206021  50.285018 -18.738618  
376  1.046693 -14.003447  -2.543588  58.895523 -24.011323  
377 -1.684907 -14.988073  -9.063218  54.972757 -32.168080

In [41]:
max_timestamps = 0

for id in df.id.values:
    if df.loc[df.id == id].iloc[:, 1].shape[0] > max_timestamps:
        max_timestamps = df.loc[df.id == id].iloc[:, 1].shape[0]

In [42]:
max_timestamps

12

In [ ]:
import numpy as np

tt = np.arange(max_timestamps)

In [44]:
arr = np.array([1,2,3])
np.stack([arr for _ in range(5)], axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [71]:
vals = df.loc[df.id == 'sub1'].iloc[:, 1:].values
dup = np.stack([vals[-1] for _ in range(max_timestamps-vals.shape[0])], axis=0)
np.vstack((vals, dup)).shape

(12, 13)

In [25]:
masks = vals
masks
masks[~np.isnan(masks)]=1
masks[np.isnan(masks)]=0
masks

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
import torch 

patient = 'sub1'
tt = torch.tensor(tt).to("cpu")
vals = torch.tensor(vals).to("cpu").to(dtype=torch.float32)
masks = torch.tensor(masks).to("cpu")


/Users/jzhu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.
/Users/jzhu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """
/Users/jzhu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [80]:
vals

tensor([[ 0.0000,  1.0000,  3.0000,  2.0000,  3.0000,  0.0000,  6.5583,  1.1190,
          3.3222,  3.3068, 14.0680, 16.1814, 20.4063],
        [ 1.0000,  1.0000,  3.0000,  2.0000,  3.0000,  6.0000,     nan,     nan,
             nan,  4.6677, 14.8232, 21.7888, 23.0817],
        [ 2.0000,  1.0000,  3.0000,  2.0000,  3.0000, 12.0000,  7.3039,  6.4043,
          4.4679,  2.1266, 13.1579, 28.0446, 17.3802],
        [ 3.0000,  1.0000,  3.0000,  2.0000,  3.0000, 18.0000,     nan,     nan,
             nan, -1.1504, 10.1786, 28.0706, 10.5604],
        [ 4.0000,  1.0000,  3.0000,  2.0000,  3.0000, 24.0000,     nan,     nan,
             nan, -3.8797, 10.1490, 31.4411,  6.7911],
        [ 5.0000,  1.0000,  3.0000,  2.0000,  3.0000, 30.0000,  4.1756,  4.7853,
          0.6693, -5.4468,  3.8173, 27.7136, -4.0076]])

In [27]:
dataset_obj = []
dataset_obj.append((patient,tt,vals,masks))

In [28]:
dataset_obj

[('sub1',
  tensor([0, 1, 2, 3, 4, 5]),
  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
         dtype=torch.float64),
  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
         dtype=torch.float64))]