In [1]:
import pandas as pd

df = pd.read_csv('data/camh/simdata_long_n100.csv')

In [2]:
df = df.drop(['time'],axis=1)

In [3]:
df.describe()

period        msex       geno1      geno2       geno3        img1  \
count  576.000000  576.000000  576.000000  576.00000  576.000000  338.000000   
mean     2.939236    0.475694    2.092014    2.50000    1.531250    5.092507   
std      2.433417    0.499843    0.860862    0.70526    0.756925    2.202294   
min      0.000000    0.000000    1.000000    1.00000    1.000000   -1.282626   
25%      1.000000    0.000000    1.000000    2.00000    1.000000    3.477248   
50%      2.000000    0.000000    2.000000    3.00000    1.000000    5.217667   
75%      5.000000    1.000000    3.000000    3.00000    2.000000    6.760312   
max     11.000000    1.000000    3.000000    3.00000    3.000000    9.581138   

             img2        img3        cog1        cog2        cog3         ses  
count  338.000000  338.000000  576.000000  576.000000  576.000000  576.000000  
mean     5.583070    1.487443    0.072221    8.510922   26.143424    7.155464  
std      2.347804    2.794654    5.187023    6.264848    9.325291   13.845764  
min     -1.085279   -9.136140  -15.375709  -12.370127    6.173004  -35.710186  
25%      4.084694   -0.311052   -3.417429    4.160082   18.623475   -2.081349  
50%      5.507415    1.528835    0.931454    9.519683   25.083042    9.667171  
75%      7.161107    3.320824    4.144244   13.331719   31.993086   17.829986  
max     12.960828   10.741341    8.537550   20.652411   58.895523   31.990867

In [56]:
df.fillna(0)

id  period  msex  geno1  geno2  geno3      img1      img2      img3  \
0      sub1       0     1      3      2      3  6.558269  1.118973  3.322161   
1      sub1       1     1      3      2      3  0.000000  0.000000  0.000000   
2      sub1       2     1      3      2      3  7.303869  6.404289  4.467941   
3      sub1       3     1      3      2      3  0.000000  0.000000  0.000000   
4      sub1       4     1      3      2      3  0.000000  0.000000  0.000000   
..      ...     ...   ...    ...    ...    ...       ...       ...       ...   
571   sub99       2     1      3      3      1  6.547179  5.872905 -1.819097   
572   sub99       3     1      3      3      1  0.000000  0.000000  0.000000   
573  sub100       0     1      3      3      1  8.558649  9.792829  0.829889   
574  sub100       1     1      3      3      1  0.000000  0.000000  0.000000   
575  sub100       2     1      3      3      1  8.639795  5.221534  2.053805   

         cog1       cog2       cog3        ses  
0    3.306796  14.067982  16.181376  20.406296  
1    4.667725  14.823239  21.788824  23.081659  
2    2.126628  13.157901  28.044555  17.380201  
3   -1.150436  10.178571  28.070641  10.560428  
4   -3.879674  10.149019  31.441126   6.791078  
..        ...        ...        ...        ...  
571  1.666579  13.328830  29.657085  15.836377  
572  2.965247   8.815308  22.600366   6.739198  
573  7.606412  17.727806  17.025372  28.668826  
574  5.748109  14.643700  17.919000  19.358732  
575  2.215304  15.405128  23.313625  21.504084  

[576 rows x 13 columns]

In [60]:
df.head(20)

id  period  msex  geno1  geno2  geno3      img1      img2      img3  \
0   sub1       0     1      3      2      3  6.558269  1.118973  3.322161   
1   sub1       1     1      3      2      3       NaN       NaN       NaN   
2   sub1       2     1      3      2      3  7.303869  6.404289  4.467941   
3   sub1       3     1      3      2      3       NaN       NaN       NaN   
4   sub1       4     1      3      2      3       NaN       NaN       NaN   
5   sub1       5     1      3      2      3  4.175648  4.785277  0.669253   
6   sub2       0     1      3      2      2  8.570555  8.219832  4.053403   
7   sub2       1     1      3      2      2       NaN       NaN       NaN   
8   sub2       2     1      3      2      2  8.769006  4.899781  3.746452   
9   sub2       3     1      3      2      2       NaN       NaN       NaN   
10  sub2       4     1      3      2      2       NaN       NaN       NaN   
11  sub2       5     1      3      2      2  3.471825  6.270383 -0.610619   
12  sub3       0     0      1      3      1  4.237572  6.285353  5.785361   
13  sub3       1     0      1      3      1       NaN       NaN       NaN   
14  sub3       2     0      1      3      1  4.630498  8.575276  5.319521   
15  sub3       3     0      1      3      1       NaN       NaN       NaN   
16  sub3       4     0      1      3      1       NaN       NaN       NaN   
17  sub3       5     0      1      3      1  2.404516  4.765884  3.451819   
18  sub3       6     0      1      3      1  0.888098  3.996477  1.172856   
19  sub3       7     0      1      3      1  1.080384  2.731844  3.795298   

        cog1       cog2       cog3        ses  
0   3.306796  14.067982  16.181376  20.406296  
1   4.667725  14.823239  21.788824  23.081659  
2   2.126628  13.157901  28.044555  17.380201  
3  -1.150436  10.178571  28.070641  10.560428  
4  -3.879674  10.149019  31.441126   6.791078  
5  -5.446756   3.817270  27.713561  -4.007553  
6   6.567907  18.495933  18.110674  29.622568  
7   3.326712  18.045754  26.472464  23.851799  
8   0.935141  15.080484  29.447042  21.382692  
9  -2.859104   9.657278  28.041931   8.769953  
10 -1.035436   5.872738  32.956663   4.706498  
11 -4.634908   0.286307  29.672272  -9.903306  
12  6.416341  10.036796   6.173004  13.244413  
13  4.648353   9.241017  14.869251  12.888419  
14  4.090344   7.608530  20.661540   4.660279  
15  0.476030   4.104788  25.561308  -0.178102  
16 -2.483222   4.064157  24.081627  -0.968038  
17 -3.741344  -1.281697  31.090306  -9.040686  
18 -5.205875  -1.887255  38.352004 -15.619395  
19 -8.196046  -6.353414  38.276028 -22.928380

In [8]:
df.describe()

period        msex       geno1      geno2       geno3        img1  \
count  576.000000  576.000000  576.000000  576.00000  576.000000  338.000000   
mean     2.939236    0.475694    2.092014    2.50000    1.531250    5.092507   
std      2.433417    0.499843    0.860862    0.70526    0.756925    2.202294   
min      0.000000    0.000000    1.000000    1.00000    1.000000   -1.282626   
25%      1.000000    0.000000    1.000000    2.00000    1.000000    3.477248   
50%      2.000000    0.000000    2.000000    3.00000    1.000000    5.217667   
75%      5.000000    1.000000    3.000000    3.00000    2.000000    6.760312   
max     11.000000    1.000000    3.000000    3.00000    3.000000    9.581138   

             img2        img3        cog1        cog2        cog3         ses  
count  338.000000  338.000000  576.000000  576.000000  576.000000  576.000000  
mean     5.583070    1.487443    0.072221    8.510922   26.143424    7.155464  
std      2.347804    2.794654    5.187023    6.264848    9.325291   13.845764  
min     -1.085279   -9.136140  -15.375709  -12.370127    6.173004  -35.710186  
25%      4.084694   -0.311052   -3.417429    4.160082   18.623475   -2.081349  
50%      5.507415    1.528835    0.931454    9.519683   25.083042    9.667171  
75%      7.161107    3.320824    4.144244   13.331719   31.993086   17.829986  
max     12.960828   10.741341    8.537550   20.652411   58.895523   31.990867

In [72]:
df.loc[df.id=='sub69']

id  period  msex  geno1  geno2  geno3  time      img1       img2  \
366  sub69       0     1      3      3      1     0  7.942824  11.050807   
367  sub69       1     1      3      3      1     6       NaN        NaN   
368  sub69       2     1      3      3      1    12  6.386433   8.181420   
369  sub69       3     1      3      3      1    18       NaN        NaN   
370  sub69       4     1      3      3      1    24       NaN        NaN   
371  sub69       5     1      3      3      1    30  3.696298   5.931797   
372  sub69       6     1      3      3      1    36  4.268842   4.541949   
373  sub69       7     1      3      3      1    42  3.452485   2.120400   
374  sub69       8     1      3      3      1    48  3.920347   1.664505   
375  sub69       9     1      3      3      1    54  4.246697   4.301326   
376  sub69      10     1      3      3      1    60  2.883523   2.674891   
377  sub69      11     1      3      3      1    66  1.881854   2.246408   

         img3       cog1       cog2       cog3        ses  
366 -2.075689   8.252405  18.057623  17.236605  26.968101  
367       NaN   6.764888  14.526613  17.475498  21.688457  
368  4.868396   3.183381  12.364513  23.861694  12.945550  
369       NaN   0.596725   9.860425  26.114127  10.136811  
370       NaN  -1.784479   6.234164  27.597313   0.595799  
371  1.705776  -3.210402   4.062567  34.508350  -3.402739  
372  1.382950  -6.003822   1.939546  35.342976  -6.366126  
373  1.793578  -8.782625   1.987248  41.977552  -9.162012  
374 -0.055124 -10.841635  -1.153497  47.021450 -18.016193  
375  4.902001 -11.404033  -2.206021  50.285018 -18.738618  
376  1.046693 -14.003447  -2.543588  58.895523 -24.011323  
377 -1.684907 -14.988073  -9.063218  54.972757 -32.168080

In [41]:
max_timestamps = 0

for id in df.id.values:
    if df.loc[df.id == id].iloc[:, 1].shape[0] > max_timestamps:
        max_timestamps = df.loc[df.id == id].iloc[:, 1].shape[0]

In [42]:
max_timestamps

12

In [ ]:
import numpy as np

tt = np.arange(max_timestamps)

In [44]:
arr = np.array([1,2,3])
np.stack([arr for _ in range(5)], axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [71]:
vals = df.loc[df.id == 'sub1'].iloc[:, 1:].values
dup = np.stack([vals[-1] for _ in range(max_timestamps-vals.shape[0])], axis=0)
np.vstack((vals, dup)).shape

(12, 13)

In [25]:
masks = vals
masks
masks[~np.isnan(masks)]=1
masks[np.isnan(masks)]=0
masks

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
import torch 

patient = 'sub1'
tt = torch.tensor(tt).to("cpu")
vals = torch.tensor(vals).to("cpu").to(dtype=torch.float32)
masks = torch.tensor(masks).to("cpu")


/Users/jzhu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.
/Users/jzhu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """
/Users/jzhu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [80]:
vals

tensor([[ 0.0000,  1.0000,  3.0000,  2.0000,  3.0000,  0.0000,  6.5583,  1.1190,
          3.3222,  3.3068, 14.0680, 16.1814, 20.4063],
        [ 1.0000,  1.0000,  3.0000,  2.0000,  3.0000,  6.0000,     nan,     nan,
             nan,  4.6677, 14.8232, 21.7888, 23.0817],
        [ 2.0000,  1.0000,  3.0000,  2.0000,  3.0000, 12.0000,  7.3039,  6.4043,
          4.4679,  2.1266, 13.1579, 28.0446, 17.3802],
        [ 3.0000,  1.0000,  3.0000,  2.0000,  3.0000, 18.0000,     nan,     nan,
             nan, -1.1504, 10.1786, 28.0706, 10.5604],
        [ 4.0000,  1.0000,  3.0000,  2.0000,  3.0000, 24.0000,     nan,     nan,
             nan, -3.8797, 10.1490, 31.4411,  6.7911],
        [ 5.0000,  1.0000,  3.0000,  2.0000,  3.0000, 30.0000,  4.1756,  4.7853,
          0.6693, -5.4468,  3.8173, 27.7136, -4.0076]])

In [27]:
dataset_obj = []
dataset_obj.append((patient,tt,vals,masks))

In [28]:
dataset_obj

[('sub1',
  tensor([0, 1, 2, 3, 4, 5]),
  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
         dtype=torch.float64),
  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
         dtype=torch.float64))]

In [47]:
import torch
b = torch.arange(3 * 3*4 ).view(3, 3,4)
b

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])

In [51]:
torch.sum(b, (0, 2))

tensor([162, 210, 258])

In [21]:
29*15

435

In [12]:
import numpy as np
import h5py

a = np.random.random(size=(100,20)) # or some such
b = np.random.random(size=(100,20)) # or some such

In [5]:
data_to_write

array([[0.03174818, 0.14836142, 0.21568872, ..., 0.35911737, 0.36512419,
        0.55636708],
       [0.05122787, 0.96689672, 0.34240174, ..., 0.65983119, 0.0991594 ,
        0.31869555],
       [0.17850234, 0.73210432, 0.47325598, ..., 0.87571319, 0.54201766,
        0.73127266],
       ...,
       [0.85015853, 0.18343273, 0.76211291, ..., 0.25797554, 0.39766598,
        0.46154578],
       [0.4646985 , 0.51045674, 0.06022966, ..., 0.56904254, 0.54232957,
        0.32060165],
       [0.02637153, 0.02039313, 0.69790437, ..., 0.08013204, 0.64790604,
        0.15423998]])

In [16]:
np.stack((a,b)).shape

(2, 100, 20)

In [17]:
with h5py.File('name-of-file.h5', 'w') as hf:
    hf.create_dataset("name-of-dataset",  data=np.stack((a,b)))

In [18]:
with h5py.File('name-of-file.h5', 'r') as hf:
    data = hf['name-of-dataset'][:]

In [19]:
data.shape

(2, 100, 20)